export default {
  locale: "fr",
  api: {
    accessToken: "TAbdyPzoQeYgVSMe4GUKoCEfYctVhcwJ",
    cloudId: 10344,
    projectId: 237466,
    modelIds: [15097],
  },
  ui: {
    bimdataLogo: false,
    menuVisible: false,
    version: false,
  },
  plugins: {
    alerts: false,
    bcf: false,
    bcfManager: false,
    buildingMaker: false,
    dwg: false,
    "dwg-layer": false,
    dxf: false,
    equipment2d: false,
    fullscreen: false,
    gauge2d: false,
    ged: false,
    measure2d: false,
    measure3d: false,
    navigationVersionsModel: false,
    pdf: false,
    pdfAnnotations: false,
    pdfExport: false,
    plan: false,
    pointCloud: false,
    pointCloudParameters: false,
    projection: false,
    properties: false,
    "right-angled": false,
    search: false,
    section: false,
    smartview: false,
    split: false,
    structure: false,
    "structure-properties": false,
    synchronization: false,
    viewer2d: false,
    "viewer2d-background": false,
    "viewer2d-drawer": false,
    "viewer2d-parameters": false,
    "viewer2d-screenshot": false,
    viewer3d: {
      edges: true,
      enableDynamicLOD: false,
      enableOffsets: false,
      help: false,
      home: false,
      modelLoader: "hidden",
      navCube: false,
      navigationVersionsModel: false,
      pivotMarker: true,
    },
    "viewer3d-parameters": false,
    "window-manager": false,
  }
};
